name: Deploy to Hostinger

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd domains/lingku.xyz/nodejs
          git pull origin master
          export PATH=$PATH:/opt/alt/alt-nodejs22/root/bin
          /opt/alt/alt-nodejs22/root/bin/npm install --production
          mkdir -p tmp && touch tmp/restart.txt
